const data = [
    {
        id:1,
        link:'https://bitlocus.com/',
        img:'/images/trade/logo1.svg',
    },
    {
        id:2,
        link:'https://whitebit.com/trade/ADK_BTC',
        img:'/images/trade/logo2.svg',
    },
    {
        id:3,
        link:'https://hitbtc.com',
        img:'/images/trade/logo3.svg',
    },
    {
        id:4,
        link:'https://global.bittrex.com/Market/Index?MarketName=BTC-ADK',
        img:'/images/trade/logo4.svg',
    },
    {
        id:5,
        link:'https://www.coinbene.com/spot/exchange/ADK_BTC',
        img:'/images/trade/logo5.svg',
    },
    {
        id:6,
        link:'https://global.bittrex.com/trade/adk-btc',
        img:'/images/trade/logo6.svg',
    },
    {
        id:7,
        link:'https://indacoin.com/',
        img:'/images/trade/logo7.svg',
    },
    {
        id:8,
        link:'https://changelly.com/',
        img:'/images/trade/logo8.svg',
    },
    {
        id:9,
        link:'https://www.cointiger.com/en-us/#/trade_center?coin=adk_btc',
        img:'/images/trade/logo9.svg',
    },
]
export default data;